### ISSUE TITLE
Implement doing qrexec calls

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-qubes#23]
It seems the API only implements receiving qrexec calls. Please correct me if I'm wrong.

**Comment by talex5** [comment]
Yes, the `RExec` module currently implements the agent - a service that listens for incoming requests. Presumably you can just make your own outbound connection if you want to act as a client, although it might make sense to put some helpers for that in this module too.

**Comment by hannesm** [comment]
this has been addressed in #39
