### ISSUE TITLE
Ignore /qubes-netmask (ipv4 branch)

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-qubes#3]
According to https://github.com/talex5/qubes-mirage-firewall/issues/9#issuecomment-249525405, `/qubes-netmask` is a decoy and you should assume `255.255.255.255` in all cases.

(copying from https://github.com/talex5/mirage-qubes/pull/2#discussion_r87844062 so we don't forget)

/cc @yomimono

**Comment by yomimono** [comment]
Fixed in #5.
